# Numpy

  ## Install

In [1]:
!pip3 install numpy --upgrade

Requirement already up-to-date: numpy in /usr/local/lib/python3.7/site-packages (1.17.4)


## Import

In [2]:
import numpy as np

## Create Array

#### Numpy array from an array

In [3]:
array_first = np.array([1,2,3,4])
array_first

array([1, 2, 3, 4])

In [4]:
numbers = [6,7,8,9]
array_second = np.array(numbers)
array_second

array([6, 7, 8, 9])

#### Numpy array initialize with zeroes

In [5]:
array_third = np.zeros((2,3))
array_third

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Numpy array initialize with ones

In [6]:
array_ones = np.ones((2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Numpy array initialize with datatype

In [7]:
array_ones_int = np.ones((2,3),dtype=np.int16)
array_ones_int

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

#### Numpy create an empty array

In [8]:
# Create new uninitialized array
array_empty = np.empty((2, 2))
array_empty

array([[-0.00000000e+000, -2.00389210e+000],
       [ 9.88131292e-324,  2.82464337e-309]])

#### Create diagonal array

In [9]:
# create 1 in diagonal and 0 else
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate new array with interval

In [10]:
# 1 - start value
# 20 - end value
# 2 - step value
array_of_odds = np.arange(1,20,2)
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
array_of_floats = np.arange(0,3,0.25)
array_of_floats

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75])

#### Create 2d array

In [12]:
array_2d = np.array([(1,2,3),(4,5,6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

#### Get dimension of an array

In [13]:
array_2d.shape

(2, 3)

In [14]:
rows, columns = array_2d.shape
print(rows)
print(columns)

2
3


#### Reshape an array

In [15]:
# 2 - rows
# 3 - columns
array_nd = np.arange(6).reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

## Print Array

#### 1d Array

In [16]:
a1 = np.arange(5)
print(a1)

[0 1 2 3 4]


#### 2d Array

In [17]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Nd Array

In [18]:
# here it interpretes two arrays of 3x4 dimension
a3 = np.arange(24).reshape(2,3,4)
print(a3)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
print(np.arange(1600))

[   0    1    2 ... 1597 1598 1599]


In [20]:
print(np.arange(1600).reshape(40,40))

[[   0    1    2 ...   37   38   39]
 [  40   41   42 ...   77   78   79]
 [  80   81   82 ...  117  118  119]
 ...
 [1480 1481 1482 ... 1517 1518 1519]
 [1520 1521 1522 ... 1557 1558 1559]
 [1560 1561 1562 ... 1597 1598 1599]]


In [21]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(1600).reshape(40,40))

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49   50   51   52   53
    54   55   56   57   58   59   60   61   62   63   64   65   66   67
    68   69   70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89   90   91   92   93
    94   95   96   97   98   99  100  101  102  103  104  105  106  107
   108  109  110  111  112  113  114  115  116  117  118  119]
 [ 120  121  122  123  124  125  126  127  128  129  130  131  132  133
   134  135  136  137  138  139  140  141  142  143  144  145  146  147
   148  149  150  151  152  153  154  155  156  157  158  159]
 [ 160  161  162  163  164  165  166  167  168  169  170  171  172  173
   174  175  176  177  178  179  180  181  182  183  184  185  186  187
   188  189  190  191  192  

In [22]:
#default is 1000
np.set_printoptions(threshold=1000)
print(np.arange(1600).reshape(40,40))

[[   0    1    2 ...   37   38   39]
 [  40   41   42 ...   77   78   79]
 [  80   81   82 ...  117  118  119]
 ...
 [1480 1481 1482 ... 1517 1518 1519]
 [1520 1521 1522 ... 1557 1558 1559]
 [1560 1561 1562 ... 1597 1598 1599]]


## Array Operations

In [23]:
a = np.array([10,10,10])
b = np.array([5,5,5])

#### Addition

In [24]:
a+b

array([15, 15, 15])

#### Subtraction

In [25]:
a-b

array([5, 5, 5])

#### Multiplication

In [26]:
a*b

array([50, 50, 50])

#### Division

In [27]:
a/b

array([2., 2., 2.])

#### Modulus

In [28]:
a%3

array([1, 1, 1])

#### Conditional Operators

In [29]:
a<15

array([ True,  True,  True])

In [30]:
b>15

array([False, False, False])

#### Nd Multiplication

In [31]:
A = np.array([(1,2),(3,4)])
B = np.array([(4,3),(2,1)])

print('A:\n',A)
print('B:\n',B)

A:
 [[1 2]
 [3 4]]
B:
 [[4 3]
 [2 1]]


In [32]:
A * B

array([[4, 6],
       [6, 4]])

#### Dot Mulitplication

In [33]:
A.dot(B)

array([[ 8,  5],
       [20, 13]])

In [34]:
np.dot(A,B)

array([[ 8,  5],
       [20, 13]])

#### Self Assignment Operators

In [35]:
a *= 2
a

array([20, 20, 20])

In [36]:
b += a
b

array([25, 25, 25])

#### Basic Functions

In [37]:
ages = np.array([10,8,7,12])

In [38]:
ages.sum()

37

In [39]:
ages.min()

7

In [40]:
ages.max()

12

In [41]:
numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
# here axis=0 means columns
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [43]:
# here axis=1 means rows
numbers.sum(axis=1)

array([ 6, 22, 38])

In [44]:
# here axis=0 means columns
numbers.max(axis=0)

array([ 8,  9, 10, 11])

In [45]:
# here axis=1 means rows
numbers.min(axis=1)

array([0, 4, 8])

## Universal Functions

### Mathematical Functions

In [46]:
angles = np.array([0,30,45,60,90])

In [47]:
angle_radians = angles * np.pi/180
angle_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [48]:
print(np.sin(angle_radians))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [49]:
angle_radians = np.radians(angles)
angle_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [50]:
print(np.cos(angle_radians))

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [51]:
print(np.tan(angle_radians))

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [52]:
sin = np.sin(angle_radians)
inv = np.arcsin(sin)
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [53]:
cos = np.cos(angle_radians)
inv = np.arccos(cos)
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [54]:
np.degrees(angle_radians)

array([ 0., 30., 45., 60., 90.])

### Statistical Functions

In [55]:
marks = np.array([31,53,97,86,12,76,74,54,64,60,66,87,54,73,65])
print(marks)

[31 53 97 86 12 76 74 54 64 60 66 87 54 73 65]


In [56]:
np.median(marks)

65.0

In [57]:
mean     = np.mean(marks)
median     = np.median(marks)
sd       = np.std(marks)
variance = np.var(marks)

print("Mean = %i"%mean)
print("Median = %i"%median)
print("Standard Deviation = %i"%sd)
print("Variance = %i"%variance)

Mean = 63
Median = 65
Standard Deviation = 20
Variance = 437


## Indexing and Slicing

In [58]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
# first index is 0
a[3]

9

In [60]:
# last index is -1
a[-3]

49

In [61]:
# index 2 is included and index 6 is excluded
a[2:6]

array([ 4,  9, 16, 25])

In [62]:
a[2:]

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [63]:
a[:6]

array([ 0,  1,  4,  9, 16, 25])

In [64]:
a[:-2]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [65]:
a[-2:]

array([64, 81])

In [66]:
# start: beginning
# end: 7
# step: 2
a[:7:2]

array([ 0,  4, 16, 36])

In [67]:
# start: beginning
# end: end
# step: -1

#Reverse of numpy array
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [68]:
students = np.array([['Amit','Arya','Jon','Cersie'],[65,87,43,83],[98,43,76,57]])
students

array([['Amit', 'Arya', 'Jon', 'Cersie'],
       ['65', '87', '43', '83'],
       ['98', '43', '76', '57']], dtype='<U6')

In [69]:
students[0]

array(['Amit', 'Arya', 'Jon', 'Cersie'], dtype='<U6')

In [70]:
students[1]

array(['65', '87', '43', '83'], dtype='<U6')

In [71]:
students[0,1]

'Arya'

In [72]:
# Intersection of 1st and 2nd row & 3nd and 4rd column
students[0:2,2:4]

array([['Jon', 'Cersie'],
       ['43', '83']], dtype='<U6')

In [73]:
# all rows of 1st column
# here 2 is excluded
students[:,1:2]

array([['Arya'],
       ['87'],
       ['43']], dtype='<U6')

In [74]:
# all rows of 1st and 2nd column
# here 3 is excluded
students[:,1:3]

array([['Arya', 'Jon'],
       ['87', '43'],
       ['43', '76']], dtype='<U6')

In [75]:
#all columns of second last row
students[-2,:]

array(['65', '87', '43', '83'], dtype='<U6')

In [76]:
# all columns of first row
students[0,...]

array(['Amit', 'Arya', 'Jon', 'Cersie'], dtype='<U6')

In [77]:
# all rows of 2nd column
students[...,1]

array(['Arya', '87', '43'], dtype='<U6')

## Iterating over Arrays

In [78]:
a = np.arange(11)**2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100]


In [79]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [80]:
students = np.array([['Amit','Arya','Jon','Cersie'],
                     [65,87,43,83],
                     [98,43,76,57]])
for i in students:
    print('i = ',i)

i =  ['Amit' 'Arya' 'Jon' 'Cersie']
i =  ['65' '87' '43' '83']
i =  ['98' '43' '76' '57']


#### Iterate using `flatten()`

In [81]:
for i in students.flatten():
    print(i)

Amit
Arya
Jon
Cersie
65
87
43
83
98
43
76
57


In [82]:
# order = 'F' means column flattening - elements in column appear together
for i in students.flatten(order='F'):
    print(i)

Amit
65
98
Arya
87
43
Jon
43
76
Cersie
83
57


In [83]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### Iterate using `nditer()`

In [84]:
# nditer - iterate elements of one by one row
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [85]:
# nditer - order = 'F' means iterate elements of one by one column
for i in np.nditer(a,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


##### flatten vs nditer
**flatten** actually returns a result array, **nditer** allows to iterate over elements

##### `external_loop` flag in `nditer`

`external_loop` returns an array.

In [86]:
for i in np.nditer(a,order='F',flags=['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


##### `readwrite` op_flag in `nditer`

In [87]:
import traceback
a = np.arange(12).reshape(3,4)
for i in np.nditer(a):
    try:
     # here arr is read only by default so it will throw error
     i[...] = i * i
    except ValueError:
        traceback.print_exc()
        break

Traceback (most recent call last):
  File "<ipython-input-87-8c1815e8c528>", line 6, in <module>
    i[...] = i * i
ValueError: assignment destination is read-only


In [88]:
a = np.arange(12).reshape(3,4)
for arr in np.nditer(a,op_flags = ['readwrite']):
    arr[...] = arr * arr
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


## Reshaping Arrays

In [89]:
cities = np.array([['Rajkot','Ahmedabad','Mumbai'],['Chennai','Kolkata','Pune']])
cities

array([['Rajkot', 'Ahmedabad', 'Mumbai'],
       ['Chennai', 'Kolkata', 'Pune']], dtype='<U9')

In [90]:
cities.shape

(2, 3)

#### Flattening to a 1d array

In [91]:
cities.ravel()

array(['Rajkot', 'Ahmedabad', 'Mumbai', 'Chennai', 'Kolkata', 'Pune'],
      dtype='<U9')

#### Transpose of an array

In [92]:
cities.T

array([['Rajkot', 'Chennai'],
       ['Ahmedabad', 'Kolkata'],
       ['Mumbai', 'Pune']], dtype='<U9')

In [93]:
cities.T.ravel()
#element in differnt orders

array(['Rajkot', 'Chennai', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Pune'],
      dtype='<U9')

#### Reshape an Array

In [94]:
print(cities)
cities.reshape(3,2)

[['Rajkot' 'Ahmedabad' 'Mumbai']
 ['Chennai' 'Kolkata' 'Pune']]


array([['Rajkot', 'Ahmedabad'],
       ['Mumbai', 'Chennai'],
       ['Kolkata', 'Pune']], dtype='<U9')

In [95]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
import traceback
try:
    np.arange(15).reshape(4,4)
except ValueError:
    traceback.print_exc()

Traceback (most recent call last):
  File "<ipython-input-97-df19d88243b7>", line 3, in <module>
    np.arange(15).reshape(4,4)
ValueError: cannot reshape array of size 15 into shape (4,4)


In [98]:
# here negative number means we don't know number of rows
# 3 columns
cities.reshape(-1,3)

array([['Rajkot', 'Ahmedabad', 'Mumbai'],
       ['Chennai', 'Kolkata', 'Pune']], dtype='<U9')

In [99]:
# here negative number means we don't know number of columns
# 3 rows
cities.reshape(3,-1)

array([['Rajkot', 'Ahmedabad'],
       ['Mumbai', 'Chennai'],
       ['Kolkata', 'Pune']], dtype='<U9')

In [100]:
import traceback
try:
    cities.reshape(4,-1)
except ValueError:
    traceback.print_exc()

Traceback (most recent call last):
  File "<ipython-input-100-b62991f143dc>", line 3, in <module>
    cities.reshape(4,-1)
ValueError: cannot reshape array of size 6 into shape (4,newaxis)


## Splitting an Array

In [101]:
a = np.arange(9)

In [102]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### Split in equal size sub-array

In [103]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

#### Split the array at positions

In [104]:
np.split(a,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

#### Split array horizontally

In [105]:
a = np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [106]:
a1, a2 = np.hsplit(a,2)
print('a1 =\n',a1)
print('a2 =\n',a2)

a1 =
 [[0 1]
 [4 5]]
a2 =
 [[2 3]
 [6 7]]


In [107]:
np.hsplit(a,4)

[array([[0],
        [4]]), array([[1],
        [5]]), array([[2],
        [6]]), array([[3],
        [7]])]

#### Split array vertically

In [108]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
a1,a2 = np.vsplit(a,2)
print('a1 =',a1)
print('a2 =',a2)

a1 = [[0 1 2 3]]
a2 = [[4 5 6 7]]


## Shallow Copies

NumPy has `view()` method which is used to create an array object that looks at the same data of the original array. Change in dimensions of the new array doesn’t change dimensions of the original, but change in data also change data in origional.

In [110]:
fruits = np.array(['Apple','Mango','Grapes','Strawberry'])

In [111]:
basket_1 = fruits.view()
basket_2 = fruits.view()

In [112]:
print(basket_1)
print(basket_2)

['Apple' 'Mango' 'Grapes' 'Strawberry']
['Apple' 'Mango' 'Grapes' 'Strawberry']


In [113]:
##Ids for the arrays are different
print(id(fruits))
print(id(basket_1))
print(id(basket_2))

4505422864
4505438528
4505372832


In [114]:
basket_1 is fruits

False

In [115]:
basket_1.base is fruits

True

In [116]:
#Also change data of an origional array
basket_2[0] = 'Banana'
print('Fruits:\n',fruits)
print('Basket 1:\n',basket_1)
print('Basket 2:\n',basket_2)

Fruits:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 1:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 2:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']


In [117]:
basket_2 is basket_1

False

In [118]:
#Doesn't change dimension of an origional array
basket_2.shape = 2,2
print('Fruits:\n',fruits)
print('Basket 1:\n',basket_1)
print('Basket 2:\n',basket_2)

Fruits:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 1:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 2:
 [['Banana' 'Mango']
 ['Grapes' 'Strawberry']]


## Deep Copies

The `copy()` function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

In [119]:
fruits = np.array(['Apple','Mango','Grapes','Strawberry'])
basket_1 = fruits.copy()
basket_2 = fruits.copy()
print('Fruits:\n',fruits)
print('Basket 1:\n',basket_1)
print('Basket 2:\n',basket_2)

Fruits:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']
Basket 1:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']
Basket 2:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']


In [120]:
#Doesn't change data of an origional array
basket_1[0]='Banana'
print('Fruits:\n',fruits)
print('Basket 1:\n',basket_1)
print('Basket 2:\n',basket_2)

Fruits:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']
Basket 1:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 2:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']


In [121]:
#Doesn't change dimension of an origional array
basket_2.shape = 2,2
print('Fruits:\n',fruits)
print('Basket 1:\n',basket_1)
print('Basket 2:\n',basket_2)

Fruits:
 ['Apple' 'Mango' 'Grapes' 'Strawberry']
Basket 1:
 ['Banana' 'Mango' 'Grapes' 'Strawberry']
Basket 2:
 [['Apple' 'Mango']
 ['Grapes' 'Strawberry']]
