# Numpy

  ## Install

In [1]:
!pip3 install numpy --upgrade

Requirement already up-to-date: numpy in /usr/local/lib/python3.7/site-packages (1.17.4)


## Import

In [2]:
import numpy as np

## Create Array

#### Numpy array from an array

In [3]:
array_first = np.array([1,2,3,4])
array_first

array([1, 2, 3, 4])

In [4]:
numbers = [6,7,8,9]
array_second = np.array(numbers)
array_second

array([6, 7, 8, 9])

#### Numpy array initialize with zeroes

In [5]:
array_third = np.zeros((2,3))
array_third

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Numpy array initialize with ones

In [6]:
array_ones = np.ones((2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Numpy array initialize with datatype

In [7]:
array_ones_int = np.ones((2,3),dtype=np.int16)
array_ones_int

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

#### Numpy create an empty array

In [8]:
# Create new uninitialized array
array_empty = np.empty((2, 2))
array_empty

array([[3.10503618e+231, 3.10503618e+231],
       [2.23224663e-314, 2.23226255e-314]])

#### Create diagonal array

In [9]:
# create 1 in diagonal and 0 else
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Generate new array with interval

In [10]:
# 1 - start value
# 20 - end value
# 2 - step value
array_of_odds = np.arange(1,20,2)
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
array_of_floats = np.arange(0,3,0.25)
array_of_floats

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75])

#### Create 2d array

In [12]:
array_2d = np.array([(1,2,3),(4,5,6)])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

#### Get dimension of an array

In [13]:
array_2d.shape

(2, 3)

In [14]:
rows, columns = array_2d.shape
print(rows)
print(columns)

2
3


#### Reshape an array

In [15]:
# 2 - rows
# 3 - columns
array_nd = np.arange(6).reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])